name: flutter_next_auth
description: A Flutter package for NextERP (Frappe/ERPNext) authentication with secure session management.
version: 1.0.0
author: Mouhanned Ben Lazreg
homepage: https://github.com/handoud/flutter_next_auth

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # This package does not contain any assets
